### ISSUE TITLE
groupex_form_cache entities is not removed correctly and make database grow

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#758] opened 2017-08-22 09:07 UTC
openy_group_schedules/modules/groupex_form_cache/src/GroupexFormCacheManager.php

private function removeByChunk(array $ids, $count = 10) {
$storage = $this->entityTypeManager->getStorage(self::ENTITY_TYPE);
$chunks = array_chunk($ids, $count);
foreach ($chunks as $chunk)
{ $entities = GroupexFormCache::loadMultiple($chunk); $storage->delete($entities); }
}

See that old cachetags are not deleted (and remaining in `cachetags` table forever)
SELECT COUNT ( * )
FROM `cachetags`
WHERE tag like 'groupex_form_cache%'

That make table grow over the time and use all storage or exceed max table size (and be locked)

**Comment by YMCA-GTC** [comment] 2017-09-17 19:24
@podarok @Sanchiz This seems like a pretty significant issue - unless you help me understand otherwise, I am marking this as critical.

**Comment by podarok** [comment] 2017-09-18 15:05
cachetags is not the table which is cleared by the cache clear. It is just a list of tags and stats about them. So no worries here.
It's even not a bug, but feature of drupal core. 
Marking this as a low priority just to track in case if something arrived with a time

**Comment by podarok** [comment] 2017-09-18 15:07
Added status needs more info. Please share real data in case if cachetags table grows up a super fast for the any project on OpenY

**Comment by david-hernandez** [comment] 2017-11-22 14:57
I agree with Andrii here. But for investigation sake, can you provide an example of the tags you are seeing and how many?

**Comment by podarok** [comment] 2018-01-04 11:30
This is closed. Reopen if you have any concerns yet

**Closed as completed by podarok** 2018-01-04 11:30 UTC
Labels: Status: Needs more info, Type: Docs, Severity: Minor
