### ISSUE TITLE
Broken Gallery Buttons on Carnation Theme

### ISSUE THREAD

**Issue by YCO-GIT** [ymcatwincities/openy#1633] opened 2019-06-25 16:59 UTC
Left and right buttons on gallery aren't working at the bottom of this page: http://134.209.45.166/locations/delaware

**Comment by paige-kiecker** [comment] 2019-06-27 13:47
This has been assigned to FJ for resolution

**Comment by AndreyMaximov** [comment] 2019-07-01 09:05
Hi @YCO-GIT @paige-kiecker 

@YCO-GIT is that a vanilla Carnation?
It seems that the Gallery paragraph template was altered.
See, the original markup for carousel navigation arrows have `carousel-control` class:
https://github.com/ymcatwincities/openy/blob/8.2.1.3/themes/openy_themes/openy_carnation/templates/field/field--paragraph--gallery-cta.html.twig#L55
https://github.com/ymcatwincities/openy/blob/8.2.1.3/themes/openy_themes/openy_carnation/templates/field/field--paragraph--gallery-cta.html.twig#L60

The [linked page](http://134.209.45.166/locations/delaware) markup is not the same. Notice the links don't have that class
![image](https://user-images.githubusercontent.com/5453109/60423939-eef87b00-9bf7-11e9-97b5-6d26f354405b.png)

The module's javascript code expects them and that probably the cause of the issue on your website. 
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_gallery/js/openy_prgf_gallery_alert.js#L8

I don't think it's Carnation theme problem. Correct me if I'm wrong.

**Comment by scottdebney** [comment] 2019-07-01 14:33
So we haven't modified any of the field twig files, and when I checked the referenced twig file on our installed dist, it looks correct? Is there another place that gallery code is pulled from or an overide somewhere? 

![image](https://user-images.githubusercontent.com/5481333/60444617-915e3180-9beb-11e9-8959-bcef595d2ccb.png)

**Comment by AndreyMaximov** [comment] 2019-07-01 15:22
Hi @scottdebney 

Please find the file of the custom theme at `<docroot>/themes/<your_custom_theme>/templates/field--paragraph--gallery-cta.html.twig`

`<docroot>` is where `index.php` is located
`<your_custom_theme>` - I'm not sure what is the name of your custom theme, but there is should be something. If there are several directories under `themes` inspect all of them.

The pointed file overrides the base theme (openy_carnation) twig template.

If there is no such file then try searching file that contains `carousel-control-next` string.

**Comment by paige-kiecker** [comment] 2019-07-16 14:56
This issue has been fixed and merged

**Closed as completed by paige-kiecker** 2019-07-16 14:56 UTC
Labels: Type: Bug, Severity: Important
