### ISSUE TITLE
Program registration paragraph does not work in Sandbox

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1197] opened 2018-07-31 15:05 UTC
There is a paragraph from the module OpenY Program Registration Paragraph. When I try to edit its settings on this page /admin/structure/paragraphs_type/program_registration/fields I get an error 
`
Drupal\daxko\DaxkoClientException: Failed to make a request for uri branches?limit=100 with message cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html). in Drupal\daxko\DaxkoClient->makeRequest() (line 63 of /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/profiles/contrib/openy/modules/custom/daxko/src/DaxkoClient.php).
`
cc @podarok , @YMCA-GTC

**Comment by ymcagtc** [comment] 2018-08-16 15:07
@ddrozdik Could you please re-test to rule out that the issue is not on Daxko's end? Once you've confirmed that, please post back here and we will investigate further. Thank you!

**Comment by ddrozdik** [comment] 2018-10-15 12:33
yes, unfortunately, this is still valid. 
Steps to reproduce: 
1. Go to http://sandbox.openymca.org
2. Login as admin 
3. Go to Home  -> Administration  -> Structure ->  Paragraphs types ->  Manage fields
4. You will see the only one field `Program registration block`
5. Click on the Edit button 
6. You will see a white screen with a message `The website encountered an unexpected error. Please try again later.` on the screen and error in logs(see above)

**Comment by YMCA-GTC** [comment] 2019-03-14 20:14
Assigned to @podarok to investigate further on a resolution if needed.

**Comment by podarok** [comment] 2019-03-15 10:55
@ddrozdik looks like by default there is no any daxko connection which leads to error.
Daxko client is not perfect, I believe it still experimental. It was introduced by @ygerasimov team and this is a good topic for discussion on some of our next calls @YMCA-GTC 

As a requirement for the task to be done - ```any client from any integration should catch Exceptions with proper messages to content managers/site admins in case if connection failed```
Does it make sense for you @ddrozdik

**Comment by Elenamarchenkova** [comment] 2020-03-18 10:49
Five Jars starts working on this issue.

**Comment by sarah-halby** [comment] 2020-10-20 15:24
Item completed on March 27, 2020.

**Closed as completed by sarah-halby** 2020-10-20 15:24 UTC
Labels: Type: Bug, Severity: Normal, Five Jars
