### ISSUE TITLE
Carnation micro site menu doesn't display

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1299] opened 2018-09-14 00:24 UTC
Go to http://sandbox.openymca.org/give and notice there is a microsite menu for Lily and Rose. Change the theme to Carnation and the microsite menu disappears.

Here it is working properly on Rose:
![image](https://user-images.githubusercontent.com/17653329/45522752-95b77c00-b78a-11e8-8357-d85b3db2b988.png)

And here it is missing on Carnation:
![image](https://user-images.githubusercontent.com/17653329/45522760-a831b580-b78a-11e8-93d2-2cdd5c9296bd.png)

**Comment by aaronjchristian** [comment] 2018-09-18 17:27
Hello everyone!

So it looks like the main issue is where OpenY imports the "**Camp Menu**" on a default install. You can see the camp menu sitting behind the main navigation bar.

It builds the camp menu into the "**Header Area**" instead of the "**Content Area**". We could move some more things around with jQuery in carnation... but I think there should be a better solution. 

![screenshot-local openy com-2018 09 18-10-29-08](https://user-images.githubusercontent.com/16310921/45705183-c2beb280-bb2d-11e8-8fa0-075ad552b247.jpg)

Please let me know if we can hook into the demo content import process for carnation and move that into the proper region for carnation.

Thanks!

**Comment by kolesnikoff** [comment] 2018-09-24 11:52
@podarok could you recommend @aaronjchristian what is the best approach to fix the issue? 
Thank you.

**Comment by YMCA-GTC** [comment] 2018-09-27 18:26
Assigned to @podarok for next steps.

**Comment by podarok** [comment] 2018-09-28 09:45
We need to decide if menu in header makes sense for Carnation theme. Because the theme is so different from Lily or Rose - it was made without expectation to have microsite menu in place of Header. I see here couple ideas
1 - Microsites menu is a nice feature to have even on Carnation, but instead of rendering it below the main navigation, I guess we could replace main navigation with microsites menu. This needs some work.
2 - We can disable microsites menu in Header.
3 - there is no way to make the change in Demo content to fit all themes. 
4 - we definitely need to show a message to a user when there is a component on a page unsupported by theme
5 - make microsites menu renderable on Carnation and let the user decide where to put it


Personally I vote for item 5 @ymcagtc @aaronjchristian @kolesnikoff @YMCA-GTC

**Comment by aaronjchristian** [comment] 2018-09-30 21:45
@podarok I would have to agree with you on #5, I think this is probably our best option.

**Comment by podarok** [comment] 2018-10-01 13:28
@ymcagtc @YMCA-GTC let's add this to our roadmap as a low priority enhancement.
Task : Frontent
Demand: low
Effort: medium
Impact: low

@aaronjchristian correct me if I'm not enough precise in estimates

**Comment by aaronjchristian** [comment] 2018-10-01 15:28
Those all seem reasonable to me @podarok.

**Comment by aaronjchristian** [comment] 2019-02-07 17:48
Hey @podarok, it's been a little while, but are you able to elaborate a bit more on your thoughts for moving this forward? 

> make microsites menu renderable on Carnation and let the user decide where to put it

Are you thinking of something in the install step or would this be done via config/admin?

Thank you!

**Comment by podarok** [comment] 2019-03-15 10:52
I think we should just enable rendering of the component and make it somehow looking not ugly @aaronjchristian 
No need to any steps during installation - user will be able to see demo content and decide if this is fine to be used or no.
So enabling/disabling - approached via simple content edit.
Makes sense for you @aaronjchristian ?

**Comment by ddrozdik** [comment] 2019-10-14 13:59
In the current Carnation theme, the microsites menu is working and displaying on the page only if this paragraph is not the first one on the list. 
![image](https://user-images.githubusercontent.com/6285570/66756939-b4afa280-eea3-11e9-975e-ffd6ce220e1a.png)
![image](https://user-images.githubusercontent.com/6285570/66757018-e1fc5080-eea3-11e9-8cb0-e21eecbb40a9.png)

The look is not perfect but it works. 

Steps to reproduce on the Sandbox:
1. Login as admin 
2. Go to http://sandbox.openymca.org/locations/downtown-ymca
3. Edit the page and add the microsites menu paragraph as the second paragraph to the Header area.
4. Go to Appearance and install Carnation as a default theme
5. Return back
6. Verify you can see the microsites menu.
![image](https://user-images.githubusercontent.com/6285570/68236083-8726c680-0015-11ea-87b7-c3d27b879ec4.png)
7. Edit the page and remove Gallery paragraph from the Header area 
![image](https://user-images.githubusercontent.com/6285570/68236573-79be0c00-0016-11ea-8aff-900b520a285c.png)
8. Check the page 
![image](https://user-images.githubusercontent.com/6285570/68236688-b0942200-0016-11ea-9362-26b8e5c8fa2e.png)

**Comment by podarok** [comment] 2020-10-20 15:29
This is fixed now 
![image](https://user-images.githubusercontent.com/563412/96608613-3da4b980-1302-11eb-8b98-8480f55aa544.png)

**Comment by sarah-halby** [comment] 2020-10-20 15:30
@ddrozdik confirming with screenshot above from @podarok

**Closed as completed by sarah-halby** 2020-10-20 15:30 UTC
Labels: Type: Enhancement, Severity: Important
