### ISSUE TITLE
1, 4 columns paragraphs styles are broken

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1156] opened 2018-07-05 13:57 UTC
1 column, 4 columns  paragraphs are looking like broken

![image](https://user-images.githubusercontent.com/4558228/42327298-0e639254-8074-11e8-88b2-2b266e063ac2.png)

Example setup at: http://sandbox.openymca.org/paragraphs

**Comment by AlexNetman** [comment] 2018-07-05 14:00
Note, that we also were having a discussion to remove  1,2,3,4 column paragraphs from distro. Or at least hide.
Because we have paragraphs of similar structure: "Columns in grid"
And "Featured Highlights" that was supposed to become primary on YMCA Twin cities.

**Comment by ymcagtc** [comment] 2018-07-05 16:23
I don't think we should remove the 1,2,3,4 column paragraphs from the distro as others may be already using it. However, I can see merit in hiding that paragraph type from future usage. We need to include some type of messaging within the distribution when editing or creating 1,2,3,4 column paragraphs that the functionality is deprecated and to use the columns in grid instead.

For now, I'm assigning to IXM just to resolve just the primary issue above, and NOT YET to hide the 1,2,3,4 column paragraphs. 

I will create a roadmap item for hiding the 1,2,3,4 column type as that's not a bug.

**Comment by paige-kiecker** [comment] 2019-08-01 14:23
Closing this as a bug; an enhancement for these paragraph types is on the roadmap.

**Closed as completed by paige-kiecker** 2019-08-01 14:23 UTC
Labels: Type: Bug, Severity: Important
