### ISSUE TITLE
Any <a> tags added via the "Source" button on WYSIWYG editor are wiped out upon next edit

### ISSUE THREAD

**Issue by ymcagtc** [ymcatwincities/openy#606] opened 2017-06-22 19:30 UTC
A Content Admin wishes to add an image to a blog post and add a link on that image so when it is clicked a site visitor is sent to another page.

When the content editor adds the link to the image using the "Source" button in the WYSIWYG editor, saves the page, and attempts to edit the page again, the <a> tag is erased.

**Steps to reproduce:**

1. Add/Edit a blog content block (such as http://sandbox.openymca.org/node/12/edit )
2. Add an image element to the page using the WYSIWYG editor.
3. Save and publish the content, then verify image has loaded correctly
4. Edit the content area, click on "Source" to edit the HTML of the content block
5. Add an <a> tag around the image created in step 2. Such as <a href="http://ymcamn.org"></a>
6. Save and publish the page. Verify the image and <a> tag work correctly.
7. Edit the content area again, click on "Source" to further edit the HTML of the content block.
8. Note that the <a> tag that was placed around the image has disappeared.

Longer term we should also add the ability to add a link to an image via the WYSIWIG editor, however in the short term we should try to resolve this issue as soon as possible.

**Comment by podarok** [comment] 2017-06-23 07:23
We did this already for Dallas and Houston 
Here is a code needs to be backported https://github.com/propeoplemd/ymcahouston/pull/600/files

The idea is Image Component was extended with link wrapper. Feel free to backport it.

**Comment by Kerby70** [comment] 2017-06-23 15:58
@podarok I have posted a pull request #614 using a patch from https://www.drupal.org/node/2511404 wondering if this issue had come up before and was rejected for some reason?

**Comment by AlexNetman** [comment] 2017-06-26 19:18
As a result of work on this issue new field was introduced:
![image](https://user-images.githubusercontent.com/4558228/27556161-2f07ee70-5abd-11e7-8514-311c9bea88e6.png)
Now you can specify a link for image in the embedding dialog. 
That is simple for editing and gives no errors on saving.

@ymcagtc Please, close the issue if your are OK with this.

**Comment by YMCA-GTC** [comment] 2017-09-17 19:12
@AlexNetman Thank you for the work-around for linking images. The underlying issue is still there when any <a> tag added via source code editing in WYSIWIG getting removed when the content is re-edited. I will lower the severity, but keep the issue open.

**Comment by podarok** [comment] 2017-09-22 12:17
I've changed this from bug to experimental feature because a lot of things can be broken via html source code editing. In case of entity_embed I don't foresee any simple solution to avoid issues with wrapping by blocks, tags of HTML entities. I think WYSIWYG editor does a great job to eliminate manually entered mistake and adding additional checkers could overcomplicate editor and introduce unexpected behaviors

**Comment by YMCA-GTC** [comment] 2018-01-04 21:30
Closing per @podarok 's feedback above given the workaround we now have.

**Closed as completed by YMCA-GTC** 2018-01-04 21:30 UTC
Labels: Level: Middle, Status: Needs review, Type: Enhancement, Severity: Important, Type: Experimental feature
