### ISSUE TITLE
'No results' message is missing

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#1336] opened 2018-10-11 13:26 UTC
When a user goes to Schedules page and selects several filter values, sometimes there are no results returned. However, it is not obvious for a user because message about this is missing. 

Sometimes, there is a text 'Sorry, no results were found with your search criteria. Please try another selection.' displayed on the page with no results. Please investigate, maybe it's related to the locations only, but the text should be always visible if no results are returned.

![image](https://user-images.githubusercontent.com/2506214/46807145-1918bd00-cd8b-11e8-87d1-c6c23fb45c80.png)

**Comment by YMCA-GTC** [comment] 2018-10-11 15:41
I feel like this is a bug, and hopefully an easy fix. I will ask IXM to take this on.

**Comment by denisbilchenko** [comment] 2018-10-22 13:46
Hi @akaleMulder, could you please provide some info from dev tools (Chrome) maybe some errors in it. Also what version of vuejs did you use vue.js or vue.min.js?

**Comment by anpolimus** [comment] 2018-12-02 15:13
@akaleMulder , @podarok I need test-case that reproduce this issue.
I was trying to get it on my local but cant find it.

**Comment by podarok** [comment] 2018-12-03 12:58
@akaleMulder https://www.ymcagbw.org/schedules/group-exercise?date=11%20Oct%202018&locations=Oscar%20Lasko%20Branch&categories=Child%20Watch
Looks like this is fixed for YMCA of Brandywine, could you confirm? 
If yes - would you like to share the code of the fix for @anpolimus to work on adopting for OpenY?


Thanks in advance

**Comment by alexschedrov** [comment] 2018-12-03 14:39
@anpolimus it's possible when you:
1. Select room filter for some location
![image](https://user-images.githubusercontent.com/1316234/49380304-0f239280-f71a-11e8-884b-f52e186d80ae.png)

2. Then select category
![image](https://user-images.githubusercontent.com/1316234/49380256-eb604c80-f719-11e8-8dec-41cd681c54e5.png)

As a result filter by room is being hidden, but it seems still active. And you'll see no results and you won't see a "No results" message. It's easier to reproduce on real production with massive dataset - https://www.ymcagbw.org/schedules/group-exercise.

**Comment by YMCA-GTC** [comment] 2019-03-26 20:13
This one is in process of being resolved and will be part of the future point release for Activity Finder

**Comment by paige-kiecker** [comment] 2019-06-27 14:47
This has been resolved by IXM

**Closed as completed by paige-kiecker** 2019-06-27 14:48 UTC
Labels: Type: Bug, Severity: Normal
