### ISSUE TITLE
Locations page looks broken on iPad 

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1152] opened 2018-07-04 10:07 UTC
URL: /locations
Sidebar Title "Amenities" is cut
And items in the list are wrapped inconsistently

Current look:
![image](https://user-images.githubusercontent.com/4558228/42268703-dbfd87f6-7f84-11e8-9b38-a020d4d7d71e.png)

Also branch teasers are looking a bit squeezed

*Suggested solution* 
Place Amenities filter above the content and make it more compact flex grid

Even more - make list of amenities collapsible 
and show initially only Featured Amenities 
(editor can tag the most frequently searched amenity terms as Featured)

Concept:
![image](https://user-images.githubusercontent.com/4558228/42270961-cf32e8ee-7f8a-11e8-9a3c-a30e71c7567f.png)

(Note, that grey boxes for each amenity item should make filters more touch-friendly)

**Comment by AlexNetman** [comment] 2018-07-04 10:12
This should also help for Mobile users. Currently "Amenities" filters are displayed at the bottom of the long page. Which is hard to reach for most visitors.

**Comment by ymcagtc** [comment] 2018-07-05 16:20
Agreed. Adding to the backlog on Trello as this is technically an enhancement and not a bug. Historically Y associations (on average) receive about 4-5% of traffic from tablets. I still agree we should enhance this feature, and I appreciate the concept, very nice!

**Comment by paige-kiecker** [comment] 2019-04-03 14:52
Closing out for redundancies. This is on the roadmap and references back here.
https://trello.com/c/j74r66zY/131-location-page-improvements-on-tablet-breakpoints-score-8

**Closed as completed by paige-kiecker** 2019-04-03 14:52 UTC
Labels: Type: Enhancement, Severity: Important
