### ISSUE TITLE
"Hide Main Menu" functionality on Microsites Menu paragraph menu doesn't work at all

### ISSUE THREAD

**Issue by AlexMBlink** [ymcatwincities/openy#834] opened 2017-10-26 15:07 UTC
Issue is replicated on YMCA of South Hampton Roads project

![image](https://user-images.githubusercontent.com/12295993/32060753-69de6554-ba78-11e7-8d9e-1ef61b42f63c.png)

**Comment by kolesnikoff** [comment] 2018-02-12 15:15
Hi @AlexMBlink,

I tried to reproduce the issue on a clear OpenY set up with the latest codebase and everything was working as expected: [https://youtu.be/bEUxscZaXcI](https://youtu.be/bEUxscZaXcI).

Could you help with reproducing this issue?

**Comment by Fant0m771** [comment] 2018-02-12 15:26
Hi @kolesnikoff try to add it for another content type and or another content zone not 'Header content'.

**Comment by kolesnikoff** [comment] 2018-02-12 15:40
Hi @Fant0m771,
Thank you for the clarification.

It won't work on any other content type, except "landing_page", because this type is hardcoded into openy_rose_preprocess_html().

Can you specify the requirements for this functionality? How was it assumed to work?

**Comment by podarok** [comment] 2018-02-23 08:10
@kolesnikoff 
When Hide Main Menu is checked - you should get no Main Menu on a node where the option exists
![image](https://user-images.githubusercontent.com/563412/36584272-b3acc506-1881-11e8-9f38-de0050bb8eb7.png)
This is needed for the ability to create fully customized pages

**Comment by kolesnikoff** [comment] 2018-02-23 09:14
@podarok, the current functionality works for Landing pages only.
Could you confirm, that I should remove this condition and make it available for any page?

**Comment by podarok** [comment] 2018-02-23 09:28
Yes @kolesnikoff if the option available for other CTs, we need to ensure it is functional everywhere

**Comment by kolesnikoff** [comment] 2018-04-26 08:34
@podarok the requested functionality is deployed. Can we close the issue?

**Comment by podarok** [comment] 2018-04-26 09:30
@kolesnikoff no need to ask me if you know it was deployed. Just close it (you should have an access, confirm please) and ping me and @ymcagtc here in a comment that this one was closed. Also, ping Kylie on your end to update contexts and Trello respectively
Thank you!

**Closed as completed** 2018-04-26 09:30 UTC
Labels: Level: Middle, Type: Bug, Severity: Important
