### ISSUE TITLE
Sandbox Issue: GroupEx Pro integration does not work 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1092] opened 2018-06-08 14:15 UTC
There is a paragraph called "Group Schedules (GroupEx Pro)". On the sandbox, you can find it on all location pages. 
Currently, this paragraph does not work and does not show results at all. 
In the logs I found this error: 
`
GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 30001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 185 of /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php).
`
This issue reproduces only on the Sandbox environment 

cc @podarok, @YMCA-GTC

**Comment by ymcagtc** [comment] 2018-06-15 16:46
Changing severity to critical, and I consider this a bug. @podarok can you resolve this next week? If not, let's assign it to IXM

**Comment by podarok** [comment] 2018-07-06 14:12
I've checked this paragraph on today's sandbox - all works without any issues
![image](https://user-images.githubusercontent.com/563412/42383368-b12cbbb6-813f-11e8-9b04-38a990d7ec82.png)
@ddrozdik could you please post steps for reproduce?
Looks like at a time you were testing there was an issue with connectivity to GroupEx, which is possible

**Closed as completed by podarok** 2018-07-06 14:12 UTC
Labels: Type: Bug, Severity: Critical

**Comment by ddrozdik** [comment] 2018-07-12 18:16
@podarok seems not relevant anymore.
