### ISSUE TITLE
Featured blog posts on mobile: Arrows are not working in utmost cases

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1140] opened 2018-07-02 11:22 UTC
URL: sandbox.openymca.org/blog

Given there are no more slides on the right
And I click on the right arrow
Then I should see slide one

![image](https://user-images.githubusercontent.com/4558228/42161211-b6f345be-7e02-11e8-851e-4cb37e0a99d1.png)

(similar behavior is done for sliders on schedules)

**Comment by ymcagtc** [comment] 2018-07-05 16:15
The intended behavior is that the right arrow when on the last blog post should do one of the following **(whichever is the least effort to build)**

- Return to the first item in the list of blog posts
- Do not display the right arrow when at the last blog post, nor display the left arrow when at the first blog post.

Assigning to IXM for resolution

**Comment by podarok** [comment] 2018-07-13 14:38
fixed in dev

**Closed as completed by podarok** 2018-07-13 14:38 UTC
Labels: Type: Bug, Severity: Normal
