### ISSUE TITLE
Remove webform min-height

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy#2477] opened 2021-06-17 21:45 UTC
`min-height` property for webform component adding too much spacing.

See https://github.com/ymcatwincities/openy/blob/b036d48f1729ed52257b8c461b816af2bb806989/themes/openy_themes/openy_carnation/src/scss/modules/_page.scss#L71

**Comment by aleevas** [comment] 2021-09-08 15:00
@dwells-tn could you please provide more information about reported problem?
How it looks like (some screenshots/screenshot will be really helpful)? How we can reproduce it?
Thank you!

**Comment by dwells-tn** [comment] 2021-09-20 15:29
Here's the original thread in the Open Y Slack: https://openy.slack.com/archives/C16R9TDB8/p1623956248034000

It's the default styling in webforms. If you have certain fields, it adds a ton of spacing to the bottom.

Best way to reproduce is to create a simple webform with a checkbox field at the bottom.

**Comment by sarah-halby** [comment] 2021-09-20 15:48
@aleevas & @hamrant please review the above ^^ cc @shelleygoetz - please update the Jira ticket to add the Slack message and these details.

**Comment by aleevas** [comment] 2021-09-23 16:20
> Here's the original thread in the Open Y Slack: https://openy.slack.com/archives/C16R9TDB8/p1623956248034000
> 
> It's the default styling in webforms. If you have certain fields, it adds a ton of spacing to the bottom.
> 
> Best way to reproduce is to create a simple webform with a checkbox field at the bottom.

@dwells-tn thank you for your response. Now it's clear enough
@sarah-halby we can proceed work with this issue
cc @hamrant

**Comment by sarah-halby** [comment] 2021-10-19 15:39
@dwells-tn this has been completed and will be included in the Nov 9 release.

**Comment by shelleygoetz** [comment] 2021-10-25 16:17
Fixed and tested, closing issue.

**Closed as completed by shelleygoetz** 2021-10-25 16:17 UTC
Labels: Level: Novice, Status: Needs work, Type: Bug, Severity: Normal, good first issue
