### ISSUE TITLE
Buttons icons

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#2011] opened 2020-05-07 07:50 UTC
When I try to add an icon to the button, I can't seem to have icons displayed properly.

Steps to Recreate:

- Log into Sandbox
- Edit any Page that contains a WYSIWYG editable field. (http://sandbox.openymca.org/about - for example)
- Add a button to the page content by clicking the 'button' icon in WYSIWYG
- Go to the Icons tab in the modal window
- Add Fontawesome icon code, i.e. fa-ad or fa-amazon
- Save the page (icons do not appear on the Button or a rectangle is displayed instead of a button)

**Comment by paige-kiecker** [comment] 2020-05-19 15:30
Thanks @akaleMulder, this seems to be an issue affecting the Fontawesome instance on the Sandbox. we will resolve this internally! 

cc: @podarok

**Comment by sarah-halby** [comment] 2020-11-24 16:08
@akaleMulder we tested this in Rose & Lily and we were able to add an icon to a button. However, we were not able to get this to save in Carnation. Was this also your experience or did you experience it on Rose & Lily as well? We believe it is actually an issue with the Bootstrap version, but Fontawesome is also a potential root cause.

**Comment by sarah-halby** [comment] 2020-12-08 14:14
@podarok there are some missing icons on Rose & Lily. This was reported in VY as well. Can we move this up in our priority? 

![image](https://user-images.githubusercontent.com/68397223/101494787-62de9d00-392d-11eb-9c32-c28dba12a741.png)

**Comment by podarok** [comment] 2020-12-08 14:33
@sarah-halby this was fixed in Drupal 9 - I'll check for backport to Drupal 8

**Closed as completed** 2020-12-08 15:23 UTC
Labels: Level: Middle, Status: Needs more info, Type: Bug, Severity: Minor, Backporting

**Comment by podarok** [comment] 2020-12-08 15:24
@akaleMulder I tested with 
![image](https://user-images.githubusercontent.com/563412/101502874-24bb9a80-397a-11eb-89c0-604885590156.png)
![image](https://user-images.githubusercontent.com/563412/101503131-749a6180-397a-11eb-8d81-a0943a89a747.png)

and it does work. So seems like fa-ad or fa-amazon are not included in free version of fontawesome.

Regarding WYSIWYG entity icons, https://github.com/ymcatwincities/openy/issues/2011#issuecomment-740644385 @sarah-halby - fixed in https://github.com/ymcatwincities/openy/pull/2329
