### ISSUE TITLE
Two columns with fixed sidebar (sticky) - sidebar not moving

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1101] opened 2018-06-19 10:50 UTC
Given I create a landing page with Layout  "Two columns with fixed sidebar (sticky)"
And I add Simple content to the body
And a promo card into sidebar
And I save
When I scroll through the resulting page
Then I expect promo card in sidebar to be always displayed in the sidebar
But it is not sticky

**Comment by ymcagtc** [comment] 2018-07-05 16:02
@AlexNetman Do you have a URL for a sample page we can test with? If not, no worries, it would just help us debug and resolve this one faster.

**Comment by podarok** [comment] 2019-04-05 09:20
Confirmed in all 3 themes.
Looks like a regression, we had this working in the past

**Comment by paige-kiecker** [comment] 2019-07-01 19:41
This was reported again via https://github.com/ymcatwincities/openy/issues/1403 and will be resolved on that ticket. Closing this one.

**Closed as completed by paige-kiecker** 2019-07-01 19:41 UTC
Labels: Type: Bug, Severity: Important
