### ISSUE TITLE
Images Not Showing in WYSIWYG

### ISSUE THREAD

**Issue by YCO-GIT** [ymcatwincities/openy#1666] opened 2019-07-26 16:14 UTC
I'm having the same issue as shown here: https://github.com/ymcatwincities/openy/issues/857
Although I have not been able to figure out how to fix it.  Basically, I'll embed an image into a simple content field and it doesn't show.  When I save the page, it shows on the page no problem.  In the editor, there is a space occupied for the image, but you just can't see it.  Cleared cache, tried switching it around from Full to Half and back, but nothing seems to show it.  Console shows no issues.

**Comment by podarok** [comment] 2019-07-30 09:10
@YCO-GIT https://youtu.be/q3FRqC-Utzw
Can't be reproduced on vanilla OpenY
We need more info to get it fixed.

**Comment by YCO-GIT** [comment] 2019-07-30 14:40
This instance of OpenY was installed only 2 weeks ago.  Here are 2 videos that show my editor settings as well as what happens when I try to embed images in a simple content field.  I have the console open so you can view its output.  Let me know anything else you need to know to troubleshoot this.  Thanks! 
https://drive.google.com/drive/folders/0BxkOVRn37czsTFpadjFMTkQwMFE?usp=sharing

**Comment by podarok** [comment] 2019-07-31 09:53
This is related to known issue for Blazy https://www.drupal.org/project/blazy/issues/3054032#comment-13193041

**Comment by podarok** [comment] 2019-07-31 09:54
For YGTC we have patch in place . But this is a workaround 
![image](https://user-images.githubusercontent.com/563412/62202583-39ede580-b392-11e9-9fe3-d013e617423e.png)

**Comment by podarok** [comment] 2019-07-31 09:57
As a quick fix @YCO-GIT  - I've enabled Full without Blazy view mode for you to be able to have it in WYSIWYG
Keep in mind that this disables Blazy for particular embed entity
![image](https://user-images.githubusercontent.com/563412/62202817-ad8ff280-b392-11e9-8623-138264145902.png)

**Comment by YCO-GIT** [comment] 2019-07-31 13:46
Thanks for looking into this.  I went and installed another instance of OpenY in another droplet to see if I would end up with the same issue and the image embed seems to work totally fine on the new one.  I wonder what caused a difference between the installs.

**Comment by sarah-halby** [comment] 2020-11-02 14:30
@podarok to try and reproduce this issue based on the latest upgrades to blazy. If he cannot reproduce, Andrii will close this ticket.

**Comment by podarok** [comment] 2020-11-03 09:18
This is fixed in latest blazy 
![image](https://user-images.githubusercontent.com/563412/97967691-40091800-1dc6-11eb-9970-f9d1b276a437.png)

**Closed as completed by podarok** 2020-11-03 09:18 UTC
Labels: Level: Advanced, Status: Needs work, Status: Under discussion, Type: Bug, Severity: Normal, dependencies
