### ISSUE TITLE
All themes visual regressions

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2135] opened 2020-09-02 14:54 UTC
1. Membership calculator images are hidden:

https://sandbox-carnation-cus.openy.org/join

![Screenshot from 2020-09-02 17-47-35](https://user-images.githubusercontent.com/13733670/92000008-b4cbc180-ed45-11ea-9c3b-18c1ba2f2a32.png)

2. Gallery/banner is broken on the sandbox

- https://sandbox-carnation-cus.openy.org/about
- https://sandbox-carnation-cus.openy.org/give
- https://sandbox-carnation-cus.openy.org/accelerator

**Comment by jwtechdesign** [comment] 2020-09-02 16:15
Also noticed that the images are broken in "program subcategory listing" paragraphs:

https://sandbox-lily-cus.openy.org/programs/health-and-fitness
https://sandbox-rose-cus.openy.org/programs/health-and-fitness
https://sandbox-carnation-cus.openy.org/programs/health-and-fitness

**Comment by hamrant** [comment] 2020-09-02 16:39
Gallery/banner issue reproduced in Open Y 8.2.6.1, works fine in current dev.

The rest of the issues with images related to blazy, but I can't reproduce it in dev release or in 8.2.6.1. Continue investigation

**Comment by hamrant** [comment] 2020-09-02 17:39
On local I have Blazy 8.x-2.0-alpha1 (No issue)
On sandbox Blazy 8.x-2.1 (With issue)

I tested dev version of blazy, here same issue, and looks like there no patch for this.
Fast solution - rollback previous version for new point release (after this we can investigate and fix this problem in blazy to have drupal 9 support with this module).
For gallery fix in carnation we need this commit - https://github.com/ymcatwincities/openy/pull/2087 in point release

**Comment by hamrant** [comment] 2020-09-04 14:16
Both issues fixed in the current dev branch, @podarok feel free to close this one

**Comment by sarah-halby** [comment] 2020-09-11 12:49
@podarok per @hamrant's comment above, is this issue ready to be closed, or are there next steps needed?

**Comment by podarok** [comment] 2020-09-11 13:25
this is fixed in both 8/9 Drupal 
/cc @hamrant

**Closed as completed** 2020-09-11 13:24 UTC
Labels: PR: Code Reviewed, Type: Bug, Five Jars
