### ISSUE TITLE
Filber by trainer who is sub for another one

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#742] opened 2017-08-08 14:08 UTC
When I select "Melissa T (sub for Eric B)"
Then I should see 'Tabata class'
http://ci.openymca.org/build2054/schedules/group-schedules?location=204&filter_date=8/07/17&class=any&filter_length=week&category=any&groupex_class=groupex_table_instructor_individual&instructor=Melissa%20T.%3Cspan%20class=%22subbed%22%20style=%22color:%20#cc0000;"><br>(sub for Eric  B.)</span>
But it's not displayed (see that HTML in URL)

Also when I go to schedule by Trainer, I should see that trainer selected in filters.
But I don't see:

![image](https://user-images.githubusercontent.com/4558228/29021715-24bbc036-7b6f-11e7-928b-92f5788ca60a.png)

**Comment by YMCA-GTC** [comment] 2017-09-17 19:28
@Sanchiz Is this a duplicate of this issue? https://github.com/ymcatwincities/openy/issues/757

**Comment by podarok** [comment] 2018-01-04 11:29
This is a duplicate of #757

**Closed as completed by podarok** 2018-01-04 11:29 UTC
Labels: Level: Advanced, Status: Needs work, Type: Bug, Severity: Important
