### ISSUE TITLE
Daxko Program Registration - Testing Needed

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2203] opened 2020-09-22 14:35 UTC
Daxko Program Registration needs to be tested to ensure testing and compatibility with Drupal 9. @podarok to provide additional details.

**Comment by dchubar-fj** [comment] 2020-10-02 07:07
Activity Finder with Daxko back-end works fine with the Open Y Lily and Carnation themes.

But it doesn’t work with the Open Y Rose theme with any back-end - Activity Finder is not loaded at all. **The problem is not related to the Daxko integration or to Drupal 9**. And is reproducible even with the current stable version of Open Y. You can see it on sandbox https://sandbox-rose-cus.openy.org/program-search

**Comment by sarah-halby** [comment] 2020-10-02 14:57
@podarok please review the above and outline the next steps for the FiveJars team here.

**Comment by podarok** [comment] 2020-10-05 13:49
@dchubar-fj could you test if Activity Finder is loading in Rose in Bottom content region?
If it does - then this is a known issue for Rose that  is also true for Virtual Y and any vuejs app in Content region of Rose

**Comment by dchubar-fj** [comment] 2020-10-05 15:49
@podarok I can't add the Activity Finder to the bottom region for testing because this issue blocks me https://www.drupal.org/project/plugin/issues/3174110
I will let you know if I find a solution.

**Comment by sarah-halby** [comment] 2020-10-14 14:09
@dchubar-fj - @podarok is working on solving this blocker to release Activity Finder.

**Comment by podarok** [comment] 2020-10-16 13:32
@dchubar-fj this is fixed now https://github.com/ymcatwincities/openy/pull/2230
You may proceed

**Comment by NightHunterSV** [comment] 2020-10-19 15:21
Checked:
The **Activity Finder Search** paragraph can be used in the bottom region of the **Landing Page** and seems it is correctly rendered in the **Rose** theme.

But in all the themes there is an error in the logs:

`Undefined offset: 1 in Drupal\openy_activity_finder\OpenyActivityFinderBackend->getWeeks() (line 68 of /var/www/docroot/profiles/contrib/openy/modules/custom/openy_activity_finder/src/OpenyActivityFinderBackend.php) `

The fix, as well as some refactoring, provided in the PR: https://github.com/ymcatwincities/openy/pull/2248

**Comment by podarok** [comment] 2020-10-28 13:14
Great. Thank you

**Closed as completed by podarok** 2020-10-28 13:14 UTC
Labels: Level: Advanced, Status: Needs work, Severity: Critical, Five Jars
