### ISSUE TITLE
Carnation mobile menu and map on Locations and Join pages

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1389] opened 2018-11-21 09:43 UTC
In the Carnation theme map is being displayed above the mobile menu on Locations and Join pages.

It blocks the user from being able to navigate through the website via Mobile Menu. I recommend fixing the position of the map.

![image](https://user-images.githubusercontent.com/1316234/48832718-789ebb00-ed82-11e8-908b-9d53ac9ec499.png)
![image](https://user-images.githubusercontent.com/1316234/48832725-7c324200-ed82-11e8-8d13-15cf722caf00.png)
![image](https://user-images.githubusercontent.com/1316234/48832728-7fc5c900-ed82-11e8-9f2d-167ff17a9b7e.png)

**Comment by denisbilchenko** [comment] 2018-12-11 15:08
Hello @Sanchiz ,
What browser and OS did you use when caught this issue? I cannot reproduce it in responsive mode of browser and on Android 9, Chrome.

Thanks.

**Comment by YMCA-GTC** [comment] 2018-12-18 15:43
Asking IXM for estimates

**Comment by alexschedrov** [comment] 2019-03-16 10:36
@denisbilchenko I used the latest Google Chrome on MacOS.

**Comment by YMCA-GTC** [comment] 2019-03-26 16:44
IXM will be taking this on shortly.

**Comment by SanyokMedved** [comment] 2019-04-11 12:04
![adaptive_ff](https://user-images.githubusercontent.com/11158496/55955531-5db5e000-5c6a-11e9-9951-27db30ad5754.png)
<img width="478" alt="chrome_iphone_7" src="https://user-images.githubusercontent.com/11158496/55955533-5db5e000-5c6a-11e9-9449-fb952dfb1722.png">
<img width="429" alt="chrome_mob_view_iphone6" src="https://user-images.githubusercontent.com/11158496/55955534-5db5e000-5c6a-11e9-9838-2234127ce9d3.png">
@Sanchiz Tested in chrome and ff on mac and chrome on Android. Cannot reproduce. Please retest it again.

**Comment by alexschedrov** [comment] 2019-04-15 13:01
@SanyokMedved I believe this has been already fixed in https://github.com/ymcatwincities/openy/pull/1392

**Comment by alexschedrov** [comment] 2019-04-22 09:40
@paige-kiecker the issue may be closed.

**Comment by paige-kiecker** [comment] 2019-04-25 15:02
Closing out, thanks @Sanchiz

**Closed as completed by paige-kiecker** 2019-04-25 15:02 UTC
Labels: Level: Middle, Type: Bug, Severity: Critical
