### ISSUE TITLE
Leaflet map's init loops forever if no location pins provided

### ISSUE THREAD

**Issue by vitaly-malashevsky** [ymcatwincities/openy#1547] opened 2019-03-11 11:34 UTC
Sometimes map fails to operate normally in case of zero location items (empty array) provided to the module.
It repeatedly triggers the following error message `Uncaught Error: Map container is already initialized.` in js console.

![image](https://user-images.githubusercontent.com/8169225/54121010-ff46d900-4401-11e9-9a10-63612991294e.png)

Based on the stack the issue is in the _setInterval_ callback which calls _map.init_ and never gets finished. https://github.com/ymcatwincities/openy/blob/fea53f8cb86fd00a9a405f1f50604d037b45b67a/modules/custom/openy_map/js/map.js#L1604-L1618

And the `data` var is an empty array.

**Comment by YMCA-GTC** [comment] 2019-03-14 21:18
Hi @podarok can you please assess this issue and help us determine the severity? From there, we will assign as appropriate for resolution.

**Comment by podarok** [comment] 2019-03-15 11:01
@YMCA-GTC this is an edge case when 0 locations within a system. Technically - no one should have this situation, there is no sense to have location finder with 0 locations, but from architecture standpoint we should cover all edge cases and limit min and max number of possible locations for security/maintainability reasons. 
So @vitaly-malashevsky good catch, thank you, but I would consider this as not critical in terms of priority issue. 
@YMCA-GTC this is a good task for @Sanchiz @ddrozdik team as they were working on Leaflet integration from the very beginning - team is in context. Unless @vitaly-malashevsky already have a fix - I'd like to ask to publish a fix for us to work on integration into distribution, if it is not time consuming for you, Vitaly.

**Comment by YMCA-GTC** [comment] 2019-03-26 16:27
I'm asking IXM to take this on along with the other map fixes tonight (March 26). Unless @vitaly-malashevsky has already implemented a fix that's awaiting a merge

**Comment by YMCA-GTC** [comment] 2019-03-26 16:33
Setting severity to normal given the edge-case nature of the issue per @podarok

**Comment by jediandrey** [comment] 2019-03-27 11:01
![Locations | Site-Install 2019-03-27 12-58-59](https://user-images.githubusercontent.com/39241474/55071036-3834ae00-5090-11e9-957e-76d72c4b666c.jpg)

I can't reproduce this issue with no location on /locations page and leaflet map. Are there any specific steps to reproduce?

**Comment by paige-kiecker** [comment] 2019-07-01 18:02
Hi @vitaly-malashevsky, are you still experiencing this issue? As you can see, we were unable to reproduce it and will move it to our backlog unless we hear from you. Thanks!

**Comment by sarah-halby** [comment] 2020-11-02 14:10
Will review again in Q1 2021 - due to edge case and inability to reproduce, we will likely close this issue.

**Comment by sarah-halby** [comment] 2020-12-11 20:37
@vitaly-malashevsky are you still experiencing this issue? We cannot reproduce the issue and we will move to our backlog unless we hear from you.

**Comment by sarah-halby** [comment] 2020-12-23 21:04
Closing out this issue due to lack of response. We can reopen this ticket if we can reproduce the issue or we receive additional information from the requestor.

**Closed as completed by sarah-halby** 2020-12-23 21:04 UTC
Labels: Status: Needs more info, Type: Bug, Severity: Minor
